name: ns-2018
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - scipy
  - numpy
  - pandas
  - seaborn
  - patsy
  - statsmodels
  - scikit-learn
  - mlxtend
  - rfpimp
  - pip
  - pip:
    - dcor
    - biokit
