name: ns-2018
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - scipy
  - numpy
  - pandas
  - seaborn
  - dcor
  - biokit
  - patsy
  - statsmodels
  - scikit-learn
  - mlxtend
  - rfpimp
